model_checkpoint:
  _target_: callbacks.wandb_callbacks.ModelCheckpointWB
  dirpath: "checkpoints/"
  filename: "{epoch:02d}"
  monitor: "val/loss" # name of the logged metric which determines when model is improving
  save_top_k: 1 # save k best models (determined by above metric)
  save_last: True # additionaly always save model from last epoch
  mode: "min" # can be "max" or "min"
  verbose: True

lr_monitor:
  _target_: pytorch_lightning.callbacks.LearningRateMonitor

stochastic_weight_avg:
  _target_: pytorch_lightning.callbacks.stochastic_weight_avg.StochasticWeightAveraging